from closs import animais_marinhos

animal1 = animais_marinhos('Golfinho', 'Cinza', 'M', 'Delfi', 'Peixes')
animal2 = animais_marinhos('Tubarão Branco', 'Cinza claro', 'F', 'Branca', 'Focas')
animal3 = animais_marinhos('Baleia Azul', 'Azul', 'F', 'Azulina', 'Plâncton')
animal4 = animais_marinhos('Polvo', 'Marrom', 'M', 'Octo', 'Crustáceos')
animal5 = animais_marinhos('Estrela do Mar', 'Laranja', 'F', 'Estrela', 'Detritos')
animal6 = animais_marinhos('Cavalo-Marinho', 'Amarelo', 'M', 'Cavalo', 'Pequenos crustáceos')
animal7 = animais_marinhos('Moreia', 'Verde escuro', 'F', 'Mora', 'Peixes pequenos')
animal8 = animais_marinhos('Tartaruga Marinha', 'Verde', 'M', 'Tarta', 'Plantas marinhas')
animal9 = animais_marinhos('Leão Marinho', 'Marrom', 'F', 'Leão', 'Peixes e lulas')
animal10 = animais_marinhos('Boto', 'Cinza', 'M', 'Boti', 'Peixes')
animal11 = animais_marinhos('Peixe-palhaço', 'Laranja e branco', 'F', 'Clowny', 'Plâncton')
animal12 = animais_marinhos('Medusa', 'Transparente', 'M', 'Jelly', 'Plâncton')
animal13 = animais_marinhos('Caranguejo', 'Vermelho', 'F', 'Crabbi', 'Detritos')
animal14 = animais_marinhos('Orca', 'Preto e branco', 'M', 'Orquinha', 'Peixes e mamíferos marinhos')
animal15 = animais_marinhos('Peixe-pedra', 'Marron', 'F', 'Pedrinho', 'Peixes pequenos')
animal16 = animais_marinhos('Narval', 'Cinza', 'M', 'Narvinho', 'Peixes')
animal17 = animais_marinhos('Moreia', 'Marrom escuro', 'F', 'Morei', 'Peixes pequenos')
animal18 = animais_marinhos('Peixe-boi', 'Cinza', 'M', 'Boi', 'Plantas aquáticas')
animal19 = animais_marinhos('Tubarão Martelo', 'Cinza claro', 'F', 'Martelo', 'Peixes')
animal20 = animais_marinhos('Polvo Gigante', 'Vermelho', 'M', 'Gigante', 'Peixes e crustáceos')
